name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      env:
        CFNDSL_VERSION: 1.4.0
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: pkumaschow/cfndsl
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        buildargs: CFNDSL_VERSION
        tags: "latest,${{ env.CFNDSL_VERSION }}"

